-- INSERTS [PLACES]

INSERT INTO "place" ("name") VALUES
-- cabinets
('gabinete01'),
('gabinete02'),
('gabinete03'),
('gabinete04'),
('gabinete05'),
('gabinete06'),
('gabinete07'),
('gabinete08'),
('gabinete09'),
('gabinete10'),
('gabinete11'),
('gabinete12'),
('gabinete13'),
('gabinete14'),
('gabinete15'),
('gabinete16'),
('gabinete17'),
('gabinete18'),
('gabinete19'),
('gabinete20'),
('presidencia'),
-- Sectors
('almoxarifado'),
('arquivo'),
('atas'),
('contabilidade'),
('CPD'),
('cerimonial'),
('jurídico'),
('diretor'),
('expediente'),
('imprensa'),
('manutenção'),
('plenário'),
('recepção'),
('recursos humanos'),
('sala de comissões'),
('secretaria'),
('TV Câmara'),
('Telefonia');

